### ISSUE TITLE
Support for "enum" type definitions

### ISSUE THREAD

**Issue by ddl-ebrown** [danielgtaylor/huma#229] opened 2024-02-05 17:20 UTC
Since Go doesn't have real enums, it's common to use type definitions for string or int in conjunction with a series of const values for the new type.

```go
type Custom string

const (
  A Custom = "a"
  B  = "b"
)
```

 I may have missed it in the code / examples and I'm not yet familiar enough with the schema generation, but it would be great if huma understood this convention to avoid needing the `enum` struct tag. This would remove the need to keep the code and schema in sync by hand.

Thanks!

**Comment by danielgtaylor** [comment] 2024-02-05 17:30
@ddl-ebrown thanks for the feedback! First, I 💯% agree it would be preferable to use Go's idiomatic enum-like types and it's what I tried to make work before landing on the current approach. Since Huma doesn't use code generation and instead uses runtime reflection to determine type information, it unfortunately doesn't get access to the information needed to make what you are suggesting work. That info is basically dropped during compilation time and not present or accessible in the binary.

If Huma adopted some code generation (e.g. running `go generate`) then it could work, but one of the selling points of Huma is that unlike some other frameworks it doesn't require any extra steps like code generation to get it working. I'm of course open to ideas on how to make enum handling better within the constraints of the language and tools we have at our disposal, so keep the ideas coming!

**Comment by danielgtaylor** [comment] 2024-02-09 16:21
Yeah, the problem is that this just isn't possible with how Go reflection works today. I'm open to ideas with examples of how this could be made to work, but for now I'm going to close this as not possible without introducing some `go:generate` extra steps.

**Closed by danielgtaylor** 2024-02-09 16:21 UTC
Labels: question

**Comment by chenjr0719** [comment] 2024-06-15 08:31
Sorry to comment on a closed issue. But I really want to have an auto-generated enum feature with huma. I'm thinking about a more straightforward but not elegant enough solution to achieve it.

First, define an Enum interface:

```golang
type Enum interface {
	GetEnumConsts() []Enum
}

```

And define custom enum as usual but with the `GetEnumConsts()` to store all related consts:

```golang
type intEnum int

const (
	intEnumOne intEnum = iota
	intEnumTwo
)

func (e intEnum) GetEnumConsts() []huma.Enum {
	return []huma.Enum{
		intEnumOne,
		intEnumTwo,
	}
}

type stringEnum string

const (
	stringEnumFoo stringEnum = "foo"
	stringEnumBar stringEnum = "bar"
)

func (e stringEnum) GetEnumConsts() []huma.Enum {
	return []huma.Enum{
		stringEnumFoo,
		stringEnumBar,
	}
}

```

And, check whether the struct field type is implemented the Enum interface or not.
If implemented, get stored consts and append them.

```golang
var (
	enumType       = reflect.TypeOf((*Enum)(nil)).Elem()
)

if f.Type.Implements(enumType) {
	
	// Get enum values
	enumValues := []any{}
	v := reflect.New(f.Type).Interface()
	for _, e := range v.(Enum).GetEnumConsts() {
		enumValues = append(enumValues, e)
	}
	fs.Enum = enumValues

}
```

It could be a workable solution, but I'm unsure if it is a good solution or not.
